
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `pitFuelTimeLossCurrent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model pitFuelTimeLossCurrent
 * 
 */
export type pitFuelTimeLossCurrentModel = runtime.Types.Result.DefaultSelection<Prisma.$pitFuelTimeLossCurrentPayload>

export type AggregatePitFuelTimeLossCurrent = {
  _count: PitFuelTimeLossCurrentCountAggregateOutputType | null
  _avg: PitFuelTimeLossCurrentAvgAggregateOutputType | null
  _sum: PitFuelTimeLossCurrentSumAggregateOutputType | null
  _min: PitFuelTimeLossCurrentMinAggregateOutputType | null
  _max: PitFuelTimeLossCurrentMaxAggregateOutputType | null
}

export type PitFuelTimeLossCurrentAvgAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  IdRPM: number | null
  RPM: number | null
}

export type PitFuelTimeLossCurrentSumAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  IdRPM: number | null
  RPM: number | null
}

export type PitFuelTimeLossCurrentMinAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  Equipment: string | null
  Status: string | null
  Reason: string | null
  Load: string | null
  Location: string | null
  UnitLoc: string | null
  OperatorName: string | null
  Crew: string | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  TimeFuelRate: Date | null
  IdRPM: number | null
  RPM: number | null
  TimeRPM: Date | null
  RefreshTime: Date | null
}

export type PitFuelTimeLossCurrentMaxAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  Equipment: string | null
  Status: string | null
  Reason: string | null
  Load: string | null
  Location: string | null
  UnitLoc: string | null
  OperatorName: string | null
  Crew: string | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  TimeFuelRate: Date | null
  IdRPM: number | null
  RPM: number | null
  TimeRPM: Date | null
  RefreshTime: Date | null
}

export type PitFuelTimeLossCurrentCountAggregateOutputType = {
  RecordId: number
  ShiftId: number
  Equipment: number
  Status: number
  Reason: number
  Load: number
  Location: number
  UnitLoc: number
  OperatorName: number
  Crew: number
  IdFuelRate: number
  FuelRate: number
  FuelLoss: number
  TimeFuelRate: number
  IdRPM: number
  RPM: number
  TimeRPM: number
  RefreshTime: number
  _all: number
}


export type PitFuelTimeLossCurrentAvgAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  IdRPM?: true
  RPM?: true
}

export type PitFuelTimeLossCurrentSumAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  IdRPM?: true
  RPM?: true
}

export type PitFuelTimeLossCurrentMinAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  Equipment?: true
  Status?: true
  Reason?: true
  Load?: true
  Location?: true
  UnitLoc?: true
  OperatorName?: true
  Crew?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  TimeFuelRate?: true
  IdRPM?: true
  RPM?: true
  TimeRPM?: true
  RefreshTime?: true
}

export type PitFuelTimeLossCurrentMaxAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  Equipment?: true
  Status?: true
  Reason?: true
  Load?: true
  Location?: true
  UnitLoc?: true
  OperatorName?: true
  Crew?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  TimeFuelRate?: true
  IdRPM?: true
  RPM?: true
  TimeRPM?: true
  RefreshTime?: true
}

export type PitFuelTimeLossCurrentCountAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  Equipment?: true
  Status?: true
  Reason?: true
  Load?: true
  Location?: true
  UnitLoc?: true
  OperatorName?: true
  Crew?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  TimeFuelRate?: true
  IdRPM?: true
  RPM?: true
  TimeRPM?: true
  RefreshTime?: true
  _all?: true
}

export type PitFuelTimeLossCurrentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which pitFuelTimeLossCurrent to aggregate.
   */
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossCurrents to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput | Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossCurrents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossCurrents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned pitFuelTimeLossCurrents
  **/
  _count?: true | PitFuelTimeLossCurrentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PitFuelTimeLossCurrentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PitFuelTimeLossCurrentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PitFuelTimeLossCurrentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PitFuelTimeLossCurrentMaxAggregateInputType
}

export type GetPitFuelTimeLossCurrentAggregateType<T extends PitFuelTimeLossCurrentAggregateArgs> = {
      [P in keyof T & keyof AggregatePitFuelTimeLossCurrent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePitFuelTimeLossCurrent[P]>
    : Prisma.GetScalarType<T[P], AggregatePitFuelTimeLossCurrent[P]>
}




export type pitFuelTimeLossCurrentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  orderBy?: Prisma.pitFuelTimeLossCurrentOrderByWithAggregationInput | Prisma.pitFuelTimeLossCurrentOrderByWithAggregationInput[]
  by: Prisma.PitFuelTimeLossCurrentScalarFieldEnum[] | Prisma.PitFuelTimeLossCurrentScalarFieldEnum
  having?: Prisma.pitFuelTimeLossCurrentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PitFuelTimeLossCurrentCountAggregateInputType | true
  _avg?: PitFuelTimeLossCurrentAvgAggregateInputType
  _sum?: PitFuelTimeLossCurrentSumAggregateInputType
  _min?: PitFuelTimeLossCurrentMinAggregateInputType
  _max?: PitFuelTimeLossCurrentMaxAggregateInputType
}

export type PitFuelTimeLossCurrentGroupByOutputType = {
  RecordId: number
  ShiftId: number | null
  Equipment: string | null
  Status: string | null
  Reason: string | null
  Load: string | null
  Location: string | null
  UnitLoc: string | null
  OperatorName: string | null
  Crew: string | null
  IdFuelRate: number
  FuelRate: number | null
  FuelLoss: number | null
  TimeFuelRate: Date | null
  IdRPM: number
  RPM: number | null
  TimeRPM: Date | null
  RefreshTime: Date | null
  _count: PitFuelTimeLossCurrentCountAggregateOutputType | null
  _avg: PitFuelTimeLossCurrentAvgAggregateOutputType | null
  _sum: PitFuelTimeLossCurrentSumAggregateOutputType | null
  _min: PitFuelTimeLossCurrentMinAggregateOutputType | null
  _max: PitFuelTimeLossCurrentMaxAggregateOutputType | null
}

type GetPitFuelTimeLossCurrentGroupByPayload<T extends pitFuelTimeLossCurrentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PitFuelTimeLossCurrentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PitFuelTimeLossCurrentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PitFuelTimeLossCurrentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PitFuelTimeLossCurrentGroupByOutputType[P]>
      }
    >
  >



export type pitFuelTimeLossCurrentWhereInput = {
  AND?: Prisma.pitFuelTimeLossCurrentWhereInput | Prisma.pitFuelTimeLossCurrentWhereInput[]
  OR?: Prisma.pitFuelTimeLossCurrentWhereInput[]
  NOT?: Prisma.pitFuelTimeLossCurrentWhereInput | Prisma.pitFuelTimeLossCurrentWhereInput[]
  RecordId?: Prisma.IntFilter<"pitFuelTimeLossCurrent"> | number
  ShiftId?: Prisma.IntNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  Equipment?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Status?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Reason?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Load?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Location?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  UnitLoc?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  OperatorName?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Crew?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  IdFuelRate?: Prisma.IntFilter<"pitFuelTimeLossCurrent"> | number
  FuelRate?: Prisma.FloatNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  FuelLoss?: Prisma.FloatNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  TimeFuelRate?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossCurrent"> | Date | string | null
  IdRPM?: Prisma.IntFilter<"pitFuelTimeLossCurrent"> | number
  RPM?: Prisma.FloatNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  TimeRPM?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossCurrent"> | Date | string | null
  RefreshTime?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossCurrent"> | Date | string | null
}

export type pitFuelTimeLossCurrentOrderByWithRelationInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrderInput | Prisma.SortOrder
  Equipment?: Prisma.SortOrderInput | Prisma.SortOrder
  Status?: Prisma.SortOrderInput | Prisma.SortOrder
  Reason?: Prisma.SortOrderInput | Prisma.SortOrder
  Load?: Prisma.SortOrderInput | Prisma.SortOrder
  Location?: Prisma.SortOrderInput | Prisma.SortOrder
  UnitLoc?: Prisma.SortOrderInput | Prisma.SortOrder
  OperatorName?: Prisma.SortOrderInput | Prisma.SortOrder
  Crew?: Prisma.SortOrderInput | Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  FuelLoss?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeRPM?: Prisma.SortOrderInput | Prisma.SortOrder
  RefreshTime?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type pitFuelTimeLossCurrentWhereUniqueInput = Prisma.AtLeast<{
  RecordId?: number
  AND?: Prisma.pitFuelTimeLossCurrentWhereInput | Prisma.pitFuelTimeLossCurrentWhereInput[]
  OR?: Prisma.pitFuelTimeLossCurrentWhereInput[]
  NOT?: Prisma.pitFuelTimeLossCurrentWhereInput | Prisma.pitFuelTimeLossCurrentWhereInput[]
  ShiftId?: Prisma.IntNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  Equipment?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Status?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Reason?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Load?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Location?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  UnitLoc?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  OperatorName?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  Crew?: Prisma.StringNullableFilter<"pitFuelTimeLossCurrent"> | string | null
  IdFuelRate?: Prisma.IntFilter<"pitFuelTimeLossCurrent"> | number
  FuelRate?: Prisma.FloatNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  FuelLoss?: Prisma.FloatNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  TimeFuelRate?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossCurrent"> | Date | string | null
  IdRPM?: Prisma.IntFilter<"pitFuelTimeLossCurrent"> | number
  RPM?: Prisma.FloatNullableFilter<"pitFuelTimeLossCurrent"> | number | null
  TimeRPM?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossCurrent"> | Date | string | null
  RefreshTime?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossCurrent"> | Date | string | null
}, "RecordId">

export type pitFuelTimeLossCurrentOrderByWithAggregationInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrderInput | Prisma.SortOrder
  Equipment?: Prisma.SortOrderInput | Prisma.SortOrder
  Status?: Prisma.SortOrderInput | Prisma.SortOrder
  Reason?: Prisma.SortOrderInput | Prisma.SortOrder
  Load?: Prisma.SortOrderInput | Prisma.SortOrder
  Location?: Prisma.SortOrderInput | Prisma.SortOrder
  UnitLoc?: Prisma.SortOrderInput | Prisma.SortOrder
  OperatorName?: Prisma.SortOrderInput | Prisma.SortOrder
  Crew?: Prisma.SortOrderInput | Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  FuelLoss?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeRPM?: Prisma.SortOrderInput | Prisma.SortOrder
  RefreshTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.pitFuelTimeLossCurrentCountOrderByAggregateInput
  _avg?: Prisma.pitFuelTimeLossCurrentAvgOrderByAggregateInput
  _max?: Prisma.pitFuelTimeLossCurrentMaxOrderByAggregateInput
  _min?: Prisma.pitFuelTimeLossCurrentMinOrderByAggregateInput
  _sum?: Prisma.pitFuelTimeLossCurrentSumOrderByAggregateInput
}

export type pitFuelTimeLossCurrentScalarWhereWithAggregatesInput = {
  AND?: Prisma.pitFuelTimeLossCurrentScalarWhereWithAggregatesInput | Prisma.pitFuelTimeLossCurrentScalarWhereWithAggregatesInput[]
  OR?: Prisma.pitFuelTimeLossCurrentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.pitFuelTimeLossCurrentScalarWhereWithAggregatesInput | Prisma.pitFuelTimeLossCurrentScalarWhereWithAggregatesInput[]
  RecordId?: Prisma.IntWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number
  ShiftId?: Prisma.IntNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number | null
  Equipment?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  Status?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  Reason?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  Load?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  Location?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  UnitLoc?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  OperatorName?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  Crew?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | string | null
  IdFuelRate?: Prisma.IntWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number
  FuelRate?: Prisma.FloatNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number | null
  FuelLoss?: Prisma.FloatNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number | null
  TimeFuelRate?: Prisma.DateTimeNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | Date | string | null
  IdRPM?: Prisma.IntWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number
  RPM?: Prisma.FloatNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | number | null
  TimeRPM?: Prisma.DateTimeNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | Date | string | null
  RefreshTime?: Prisma.DateTimeNullableWithAggregatesFilter<"pitFuelTimeLossCurrent"> | Date | string | null
}

export type pitFuelTimeLossCurrentCreateInput = {
  ShiftId?: number | null
  Equipment?: string | null
  Status?: string | null
  Reason?: string | null
  Load?: string | null
  Location?: string | null
  UnitLoc?: string | null
  OperatorName?: string | null
  Crew?: string | null
  IdFuelRate: number
  FuelRate?: number | null
  FuelLoss?: number | null
  TimeFuelRate?: Date | string | null
  IdRPM: number
  RPM?: number | null
  TimeRPM?: Date | string | null
  RefreshTime?: Date | string | null
}

export type pitFuelTimeLossCurrentUncheckedCreateInput = {
  RecordId?: number
  ShiftId?: number | null
  Equipment?: string | null
  Status?: string | null
  Reason?: string | null
  Load?: string | null
  Location?: string | null
  UnitLoc?: string | null
  OperatorName?: string | null
  Crew?: string | null
  IdFuelRate: number
  FuelRate?: number | null
  FuelLoss?: number | null
  TimeFuelRate?: Date | string | null
  IdRPM: number
  RPM?: number | null
  TimeRPM?: Date | string | null
  RefreshTime?: Date | string | null
}

export type pitFuelTimeLossCurrentUpdateInput = {
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossCurrentUncheckedUpdateInput = {
  RecordId?: Prisma.IntFieldUpdateOperationsInput | number
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossCurrentCreateManyInput = {
  ShiftId?: number | null
  Equipment?: string | null
  Status?: string | null
  Reason?: string | null
  Load?: string | null
  Location?: string | null
  UnitLoc?: string | null
  OperatorName?: string | null
  Crew?: string | null
  IdFuelRate: number
  FuelRate?: number | null
  FuelLoss?: number | null
  TimeFuelRate?: Date | string | null
  IdRPM: number
  RPM?: number | null
  TimeRPM?: Date | string | null
  RefreshTime?: Date | string | null
}

export type pitFuelTimeLossCurrentUpdateManyMutationInput = {
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossCurrentUncheckedUpdateManyInput = {
  RecordId?: Prisma.IntFieldUpdateOperationsInput | number
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossCurrentCountOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  Equipment?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  Load?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  UnitLoc?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
  TimeRPM?: Prisma.SortOrder
  RefreshTime?: Prisma.SortOrder
}

export type pitFuelTimeLossCurrentAvgOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
}

export type pitFuelTimeLossCurrentMaxOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  Equipment?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  Load?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  UnitLoc?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
  TimeRPM?: Prisma.SortOrder
  RefreshTime?: Prisma.SortOrder
}

export type pitFuelTimeLossCurrentMinOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  Equipment?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  Load?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  UnitLoc?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
  TimeRPM?: Prisma.SortOrder
  RefreshTime?: Prisma.SortOrder
}

export type pitFuelTimeLossCurrentSumOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
}



export type pitFuelTimeLossCurrentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  RecordId?: boolean
  ShiftId?: boolean
  Equipment?: boolean
  Status?: boolean
  Reason?: boolean
  Load?: boolean
  Location?: boolean
  UnitLoc?: boolean
  OperatorName?: boolean
  Crew?: boolean
  IdFuelRate?: boolean
  FuelRate?: boolean
  FuelLoss?: boolean
  TimeFuelRate?: boolean
  IdRPM?: boolean
  RPM?: boolean
  TimeRPM?: boolean
  RefreshTime?: boolean
}, ExtArgs["result"]["pitFuelTimeLossCurrent"]>



export type pitFuelTimeLossCurrentSelectScalar = {
  RecordId?: boolean
  ShiftId?: boolean
  Equipment?: boolean
  Status?: boolean
  Reason?: boolean
  Load?: boolean
  Location?: boolean
  UnitLoc?: boolean
  OperatorName?: boolean
  Crew?: boolean
  IdFuelRate?: boolean
  FuelRate?: boolean
  FuelLoss?: boolean
  TimeFuelRate?: boolean
  IdRPM?: boolean
  RPM?: boolean
  TimeRPM?: boolean
  RefreshTime?: boolean
}

export type pitFuelTimeLossCurrentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"RecordId" | "ShiftId" | "Equipment" | "Status" | "Reason" | "Load" | "Location" | "UnitLoc" | "OperatorName" | "Crew" | "IdFuelRate" | "FuelRate" | "FuelLoss" | "TimeFuelRate" | "IdRPM" | "RPM" | "TimeRPM" | "RefreshTime", ExtArgs["result"]["pitFuelTimeLossCurrent"]>

export type $pitFuelTimeLossCurrentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "pitFuelTimeLossCurrent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    RecordId: number
    ShiftId: number | null
    Equipment: string | null
    Status: string | null
    Reason: string | null
    Load: string | null
    Location: string | null
    UnitLoc: string | null
    OperatorName: string | null
    Crew: string | null
    IdFuelRate: number
    FuelRate: number | null
    FuelLoss: number | null
    TimeFuelRate: Date | null
    IdRPM: number
    RPM: number | null
    TimeRPM: Date | null
    RefreshTime: Date | null
  }, ExtArgs["result"]["pitFuelTimeLossCurrent"]>
  composites: {}
}

export type pitFuelTimeLossCurrentGetPayload<S extends boolean | null | undefined | pitFuelTimeLossCurrentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload, S>

export type pitFuelTimeLossCurrentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<pitFuelTimeLossCurrentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PitFuelTimeLossCurrentCountAggregateInputType | true
  }

export interface pitFuelTimeLossCurrentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['pitFuelTimeLossCurrent'], meta: { name: 'pitFuelTimeLossCurrent' } }
  /**
   * Find zero or one PitFuelTimeLossCurrent that matches the filter.
   * @param {pitFuelTimeLossCurrentFindUniqueArgs} args - Arguments to find a PitFuelTimeLossCurrent
   * @example
   * // Get one PitFuelTimeLossCurrent
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends pitFuelTimeLossCurrentFindUniqueArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PitFuelTimeLossCurrent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {pitFuelTimeLossCurrentFindUniqueOrThrowArgs} args - Arguments to find a PitFuelTimeLossCurrent
   * @example
   * // Get one PitFuelTimeLossCurrent
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends pitFuelTimeLossCurrentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PitFuelTimeLossCurrent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossCurrentFindFirstArgs} args - Arguments to find a PitFuelTimeLossCurrent
   * @example
   * // Get one PitFuelTimeLossCurrent
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends pitFuelTimeLossCurrentFindFirstArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossCurrentFindFirstArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PitFuelTimeLossCurrent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossCurrentFindFirstOrThrowArgs} args - Arguments to find a PitFuelTimeLossCurrent
   * @example
   * // Get one PitFuelTimeLossCurrent
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends pitFuelTimeLossCurrentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossCurrentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PitFuelTimeLossCurrents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossCurrentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PitFuelTimeLossCurrents
   * const pitFuelTimeLossCurrents = await prisma.pitFuelTimeLossCurrent.findMany()
   * 
   * // Get first 10 PitFuelTimeLossCurrents
   * const pitFuelTimeLossCurrents = await prisma.pitFuelTimeLossCurrent.findMany({ take: 10 })
   * 
   * // Only select the `RecordId`
   * const pitFuelTimeLossCurrentWithRecordIdOnly = await prisma.pitFuelTimeLossCurrent.findMany({ select: { RecordId: true } })
   * 
   */
  findMany<T extends pitFuelTimeLossCurrentFindManyArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossCurrentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PitFuelTimeLossCurrent.
   * @param {pitFuelTimeLossCurrentCreateArgs} args - Arguments to create a PitFuelTimeLossCurrent.
   * @example
   * // Create one PitFuelTimeLossCurrent
   * const PitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.create({
   *   data: {
   *     // ... data to create a PitFuelTimeLossCurrent
   *   }
   * })
   * 
   */
  create<T extends pitFuelTimeLossCurrentCreateArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentCreateArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PitFuelTimeLossCurrents.
   * @param {pitFuelTimeLossCurrentCreateManyArgs} args - Arguments to create many PitFuelTimeLossCurrents.
   * @example
   * // Create many PitFuelTimeLossCurrents
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends pitFuelTimeLossCurrentCreateManyArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossCurrentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PitFuelTimeLossCurrent.
   * @param {pitFuelTimeLossCurrentDeleteArgs} args - Arguments to delete one PitFuelTimeLossCurrent.
   * @example
   * // Delete one PitFuelTimeLossCurrent
   * const PitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.delete({
   *   where: {
   *     // ... filter to delete one PitFuelTimeLossCurrent
   *   }
   * })
   * 
   */
  delete<T extends pitFuelTimeLossCurrentDeleteArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentDeleteArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PitFuelTimeLossCurrent.
   * @param {pitFuelTimeLossCurrentUpdateArgs} args - Arguments to update one PitFuelTimeLossCurrent.
   * @example
   * // Update one PitFuelTimeLossCurrent
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends pitFuelTimeLossCurrentUpdateArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentUpdateArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PitFuelTimeLossCurrents.
   * @param {pitFuelTimeLossCurrentDeleteManyArgs} args - Arguments to filter PitFuelTimeLossCurrents to delete.
   * @example
   * // Delete a few PitFuelTimeLossCurrents
   * const { count } = await prisma.pitFuelTimeLossCurrent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends pitFuelTimeLossCurrentDeleteManyArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossCurrentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PitFuelTimeLossCurrents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossCurrentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PitFuelTimeLossCurrents
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends pitFuelTimeLossCurrentUpdateManyArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PitFuelTimeLossCurrent.
   * @param {pitFuelTimeLossCurrentUpsertArgs} args - Arguments to update or create a PitFuelTimeLossCurrent.
   * @example
   * // Update or create a PitFuelTimeLossCurrent
   * const pitFuelTimeLossCurrent = await prisma.pitFuelTimeLossCurrent.upsert({
   *   create: {
   *     // ... data to create a PitFuelTimeLossCurrent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PitFuelTimeLossCurrent we want to update
   *   }
   * })
   */
  upsert<T extends pitFuelTimeLossCurrentUpsertArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossCurrentUpsertArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossCurrentClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossCurrentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PitFuelTimeLossCurrents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossCurrentCountArgs} args - Arguments to filter PitFuelTimeLossCurrents to count.
   * @example
   * // Count the number of PitFuelTimeLossCurrents
   * const count = await prisma.pitFuelTimeLossCurrent.count({
   *   where: {
   *     // ... the filter for the PitFuelTimeLossCurrents we want to count
   *   }
   * })
  **/
  count<T extends pitFuelTimeLossCurrentCountArgs>(
    args?: Prisma.Subset<T, pitFuelTimeLossCurrentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PitFuelTimeLossCurrentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PitFuelTimeLossCurrent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PitFuelTimeLossCurrentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PitFuelTimeLossCurrentAggregateArgs>(args: Prisma.Subset<T, PitFuelTimeLossCurrentAggregateArgs>): Prisma.PrismaPromise<GetPitFuelTimeLossCurrentAggregateType<T>>

  /**
   * Group by PitFuelTimeLossCurrent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossCurrentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends pitFuelTimeLossCurrentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: pitFuelTimeLossCurrentGroupByArgs['orderBy'] }
      : { orderBy?: pitFuelTimeLossCurrentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, pitFuelTimeLossCurrentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPitFuelTimeLossCurrentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the pitFuelTimeLossCurrent model
 */
readonly fields: pitFuelTimeLossCurrentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for pitFuelTimeLossCurrent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__pitFuelTimeLossCurrentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the pitFuelTimeLossCurrent model
 */
export interface pitFuelTimeLossCurrentFieldRefs {
  readonly RecordId: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Int'>
  readonly ShiftId: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Int'>
  readonly Equipment: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly Status: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly Reason: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly Load: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly Location: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly UnitLoc: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly OperatorName: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly Crew: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'String'>
  readonly IdFuelRate: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Int'>
  readonly FuelRate: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Float'>
  readonly FuelLoss: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Float'>
  readonly TimeFuelRate: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'DateTime'>
  readonly IdRPM: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Int'>
  readonly RPM: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'Float'>
  readonly TimeRPM: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'DateTime'>
  readonly RefreshTime: Prisma.FieldRef<"pitFuelTimeLossCurrent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * pitFuelTimeLossCurrent findUnique
 */
export type pitFuelTimeLossCurrentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossCurrent to fetch.
   */
  where: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
}

/**
 * pitFuelTimeLossCurrent findUniqueOrThrow
 */
export type pitFuelTimeLossCurrentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossCurrent to fetch.
   */
  where: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
}

/**
 * pitFuelTimeLossCurrent findFirst
 */
export type pitFuelTimeLossCurrentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossCurrent to fetch.
   */
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossCurrents to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput | Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for pitFuelTimeLossCurrents.
   */
  cursor?: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossCurrents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossCurrents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pitFuelTimeLossCurrents.
   */
  distinct?: Prisma.PitFuelTimeLossCurrentScalarFieldEnum | Prisma.PitFuelTimeLossCurrentScalarFieldEnum[]
}

/**
 * pitFuelTimeLossCurrent findFirstOrThrow
 */
export type pitFuelTimeLossCurrentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossCurrent to fetch.
   */
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossCurrents to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput | Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for pitFuelTimeLossCurrents.
   */
  cursor?: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossCurrents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossCurrents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pitFuelTimeLossCurrents.
   */
  distinct?: Prisma.PitFuelTimeLossCurrentScalarFieldEnum | Prisma.PitFuelTimeLossCurrentScalarFieldEnum[]
}

/**
 * pitFuelTimeLossCurrent findMany
 */
export type pitFuelTimeLossCurrentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossCurrents to fetch.
   */
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossCurrents to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput | Prisma.pitFuelTimeLossCurrentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing pitFuelTimeLossCurrents.
   */
  cursor?: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossCurrents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossCurrents.
   */
  skip?: number
  distinct?: Prisma.PitFuelTimeLossCurrentScalarFieldEnum | Prisma.PitFuelTimeLossCurrentScalarFieldEnum[]
}

/**
 * pitFuelTimeLossCurrent create
 */
export type pitFuelTimeLossCurrentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * The data needed to create a pitFuelTimeLossCurrent.
   */
  data: Prisma.XOR<Prisma.pitFuelTimeLossCurrentCreateInput, Prisma.pitFuelTimeLossCurrentUncheckedCreateInput>
}

/**
 * pitFuelTimeLossCurrent createMany
 */
export type pitFuelTimeLossCurrentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many pitFuelTimeLossCurrents.
   */
  data: Prisma.pitFuelTimeLossCurrentCreateManyInput | Prisma.pitFuelTimeLossCurrentCreateManyInput[]
}

/**
 * pitFuelTimeLossCurrent update
 */
export type pitFuelTimeLossCurrentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * The data needed to update a pitFuelTimeLossCurrent.
   */
  data: Prisma.XOR<Prisma.pitFuelTimeLossCurrentUpdateInput, Prisma.pitFuelTimeLossCurrentUncheckedUpdateInput>
  /**
   * Choose, which pitFuelTimeLossCurrent to update.
   */
  where: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
}

/**
 * pitFuelTimeLossCurrent updateMany
 */
export type pitFuelTimeLossCurrentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update pitFuelTimeLossCurrents.
   */
  data: Prisma.XOR<Prisma.pitFuelTimeLossCurrentUpdateManyMutationInput, Prisma.pitFuelTimeLossCurrentUncheckedUpdateManyInput>
  /**
   * Filter which pitFuelTimeLossCurrents to update
   */
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  /**
   * Limit how many pitFuelTimeLossCurrents to update.
   */
  limit?: number
}

/**
 * pitFuelTimeLossCurrent upsert
 */
export type pitFuelTimeLossCurrentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * The filter to search for the pitFuelTimeLossCurrent to update in case it exists.
   */
  where: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
  /**
   * In case the pitFuelTimeLossCurrent found by the `where` argument doesn't exist, create a new pitFuelTimeLossCurrent with this data.
   */
  create: Prisma.XOR<Prisma.pitFuelTimeLossCurrentCreateInput, Prisma.pitFuelTimeLossCurrentUncheckedCreateInput>
  /**
   * In case the pitFuelTimeLossCurrent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.pitFuelTimeLossCurrentUpdateInput, Prisma.pitFuelTimeLossCurrentUncheckedUpdateInput>
}

/**
 * pitFuelTimeLossCurrent delete
 */
export type pitFuelTimeLossCurrentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
  /**
   * Filter which pitFuelTimeLossCurrent to delete.
   */
  where: Prisma.pitFuelTimeLossCurrentWhereUniqueInput
}

/**
 * pitFuelTimeLossCurrent deleteMany
 */
export type pitFuelTimeLossCurrentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which pitFuelTimeLossCurrents to delete
   */
  where?: Prisma.pitFuelTimeLossCurrentWhereInput
  /**
   * Limit how many pitFuelTimeLossCurrents to delete.
   */
  limit?: number
}

/**
 * pitFuelTimeLossCurrent without action
 */
export type pitFuelTimeLossCurrentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossCurrent
   */
  select?: Prisma.pitFuelTimeLossCurrentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossCurrent
   */
  omit?: Prisma.pitFuelTimeLossCurrentOmit<ExtArgs> | null
}
