
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `pitFuelTimeLossShift` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model pitFuelTimeLossShift
 * 
 */
export type pitFuelTimeLossShiftModel = runtime.Types.Result.DefaultSelection<Prisma.$pitFuelTimeLossShiftPayload>

export type AggregatePitFuelTimeLossShift = {
  _count: PitFuelTimeLossShiftCountAggregateOutputType | null
  _avg: PitFuelTimeLossShiftAvgAggregateOutputType | null
  _sum: PitFuelTimeLossShiftSumAggregateOutputType | null
  _min: PitFuelTimeLossShiftMinAggregateOutputType | null
  _max: PitFuelTimeLossShiftMaxAggregateOutputType | null
}

export type PitFuelTimeLossShiftAvgAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  IdRPM: number | null
  RPM: number | null
}

export type PitFuelTimeLossShiftSumAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  IdRPM: number | null
  RPM: number | null
}

export type PitFuelTimeLossShiftMinAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  Equipment: string | null
  Status: string | null
  Reason: string | null
  Load: string | null
  Location: string | null
  UnitLoc: string | null
  OperatorName: string | null
  Crew: string | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  TimeFuelRate: Date | null
  IdRPM: number | null
  RPM: number | null
  TimeRPM: Date | null
  RefreshTime: Date | null
}

export type PitFuelTimeLossShiftMaxAggregateOutputType = {
  RecordId: number | null
  ShiftId: number | null
  Equipment: string | null
  Status: string | null
  Reason: string | null
  Load: string | null
  Location: string | null
  UnitLoc: string | null
  OperatorName: string | null
  Crew: string | null
  IdFuelRate: number | null
  FuelRate: number | null
  FuelLoss: number | null
  TimeFuelRate: Date | null
  IdRPM: number | null
  RPM: number | null
  TimeRPM: Date | null
  RefreshTime: Date | null
}

export type PitFuelTimeLossShiftCountAggregateOutputType = {
  RecordId: number
  ShiftId: number
  Equipment: number
  Status: number
  Reason: number
  Load: number
  Location: number
  UnitLoc: number
  OperatorName: number
  Crew: number
  IdFuelRate: number
  FuelRate: number
  FuelLoss: number
  TimeFuelRate: number
  IdRPM: number
  RPM: number
  TimeRPM: number
  RefreshTime: number
  _all: number
}


export type PitFuelTimeLossShiftAvgAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  IdRPM?: true
  RPM?: true
}

export type PitFuelTimeLossShiftSumAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  IdRPM?: true
  RPM?: true
}

export type PitFuelTimeLossShiftMinAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  Equipment?: true
  Status?: true
  Reason?: true
  Load?: true
  Location?: true
  UnitLoc?: true
  OperatorName?: true
  Crew?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  TimeFuelRate?: true
  IdRPM?: true
  RPM?: true
  TimeRPM?: true
  RefreshTime?: true
}

export type PitFuelTimeLossShiftMaxAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  Equipment?: true
  Status?: true
  Reason?: true
  Load?: true
  Location?: true
  UnitLoc?: true
  OperatorName?: true
  Crew?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  TimeFuelRate?: true
  IdRPM?: true
  RPM?: true
  TimeRPM?: true
  RefreshTime?: true
}

export type PitFuelTimeLossShiftCountAggregateInputType = {
  RecordId?: true
  ShiftId?: true
  Equipment?: true
  Status?: true
  Reason?: true
  Load?: true
  Location?: true
  UnitLoc?: true
  OperatorName?: true
  Crew?: true
  IdFuelRate?: true
  FuelRate?: true
  FuelLoss?: true
  TimeFuelRate?: true
  IdRPM?: true
  RPM?: true
  TimeRPM?: true
  RefreshTime?: true
  _all?: true
}

export type PitFuelTimeLossShiftAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which pitFuelTimeLossShift to aggregate.
   */
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossShifts to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossShiftOrderByWithRelationInput | Prisma.pitFuelTimeLossShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.pitFuelTimeLossShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned pitFuelTimeLossShifts
  **/
  _count?: true | PitFuelTimeLossShiftCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PitFuelTimeLossShiftAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PitFuelTimeLossShiftSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PitFuelTimeLossShiftMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PitFuelTimeLossShiftMaxAggregateInputType
}

export type GetPitFuelTimeLossShiftAggregateType<T extends PitFuelTimeLossShiftAggregateArgs> = {
      [P in keyof T & keyof AggregatePitFuelTimeLossShift]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePitFuelTimeLossShift[P]>
    : Prisma.GetScalarType<T[P], AggregatePitFuelTimeLossShift[P]>
}




export type pitFuelTimeLossShiftGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  orderBy?: Prisma.pitFuelTimeLossShiftOrderByWithAggregationInput | Prisma.pitFuelTimeLossShiftOrderByWithAggregationInput[]
  by: Prisma.PitFuelTimeLossShiftScalarFieldEnum[] | Prisma.PitFuelTimeLossShiftScalarFieldEnum
  having?: Prisma.pitFuelTimeLossShiftScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PitFuelTimeLossShiftCountAggregateInputType | true
  _avg?: PitFuelTimeLossShiftAvgAggregateInputType
  _sum?: PitFuelTimeLossShiftSumAggregateInputType
  _min?: PitFuelTimeLossShiftMinAggregateInputType
  _max?: PitFuelTimeLossShiftMaxAggregateInputType
}

export type PitFuelTimeLossShiftGroupByOutputType = {
  RecordId: number
  ShiftId: number | null
  Equipment: string | null
  Status: string | null
  Reason: string | null
  Load: string | null
  Location: string | null
  UnitLoc: string | null
  OperatorName: string | null
  Crew: string | null
  IdFuelRate: number
  FuelRate: number | null
  FuelLoss: number | null
  TimeFuelRate: Date | null
  IdRPM: number
  RPM: number | null
  TimeRPM: Date | null
  RefreshTime: Date | null
  _count: PitFuelTimeLossShiftCountAggregateOutputType | null
  _avg: PitFuelTimeLossShiftAvgAggregateOutputType | null
  _sum: PitFuelTimeLossShiftSumAggregateOutputType | null
  _min: PitFuelTimeLossShiftMinAggregateOutputType | null
  _max: PitFuelTimeLossShiftMaxAggregateOutputType | null
}

type GetPitFuelTimeLossShiftGroupByPayload<T extends pitFuelTimeLossShiftGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PitFuelTimeLossShiftGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PitFuelTimeLossShiftGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PitFuelTimeLossShiftGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PitFuelTimeLossShiftGroupByOutputType[P]>
      }
    >
  >



export type pitFuelTimeLossShiftWhereInput = {
  AND?: Prisma.pitFuelTimeLossShiftWhereInput | Prisma.pitFuelTimeLossShiftWhereInput[]
  OR?: Prisma.pitFuelTimeLossShiftWhereInput[]
  NOT?: Prisma.pitFuelTimeLossShiftWhereInput | Prisma.pitFuelTimeLossShiftWhereInput[]
  RecordId?: Prisma.IntFilter<"pitFuelTimeLossShift"> | number
  ShiftId?: Prisma.IntNullableFilter<"pitFuelTimeLossShift"> | number | null
  Equipment?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Status?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Reason?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Load?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Location?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  UnitLoc?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  OperatorName?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Crew?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  IdFuelRate?: Prisma.IntFilter<"pitFuelTimeLossShift"> | number
  FuelRate?: Prisma.FloatNullableFilter<"pitFuelTimeLossShift"> | number | null
  FuelLoss?: Prisma.FloatNullableFilter<"pitFuelTimeLossShift"> | number | null
  TimeFuelRate?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossShift"> | Date | string | null
  IdRPM?: Prisma.IntFilter<"pitFuelTimeLossShift"> | number
  RPM?: Prisma.FloatNullableFilter<"pitFuelTimeLossShift"> | number | null
  TimeRPM?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossShift"> | Date | string | null
  RefreshTime?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossShift"> | Date | string | null
}

export type pitFuelTimeLossShiftOrderByWithRelationInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrderInput | Prisma.SortOrder
  Equipment?: Prisma.SortOrderInput | Prisma.SortOrder
  Status?: Prisma.SortOrderInput | Prisma.SortOrder
  Reason?: Prisma.SortOrderInput | Prisma.SortOrder
  Load?: Prisma.SortOrderInput | Prisma.SortOrder
  Location?: Prisma.SortOrderInput | Prisma.SortOrder
  UnitLoc?: Prisma.SortOrderInput | Prisma.SortOrder
  OperatorName?: Prisma.SortOrderInput | Prisma.SortOrder
  Crew?: Prisma.SortOrderInput | Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  FuelLoss?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeRPM?: Prisma.SortOrderInput | Prisma.SortOrder
  RefreshTime?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type pitFuelTimeLossShiftWhereUniqueInput = Prisma.AtLeast<{
  RecordId?: number
  AND?: Prisma.pitFuelTimeLossShiftWhereInput | Prisma.pitFuelTimeLossShiftWhereInput[]
  OR?: Prisma.pitFuelTimeLossShiftWhereInput[]
  NOT?: Prisma.pitFuelTimeLossShiftWhereInput | Prisma.pitFuelTimeLossShiftWhereInput[]
  ShiftId?: Prisma.IntNullableFilter<"pitFuelTimeLossShift"> | number | null
  Equipment?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Status?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Reason?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Load?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Location?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  UnitLoc?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  OperatorName?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  Crew?: Prisma.StringNullableFilter<"pitFuelTimeLossShift"> | string | null
  IdFuelRate?: Prisma.IntFilter<"pitFuelTimeLossShift"> | number
  FuelRate?: Prisma.FloatNullableFilter<"pitFuelTimeLossShift"> | number | null
  FuelLoss?: Prisma.FloatNullableFilter<"pitFuelTimeLossShift"> | number | null
  TimeFuelRate?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossShift"> | Date | string | null
  IdRPM?: Prisma.IntFilter<"pitFuelTimeLossShift"> | number
  RPM?: Prisma.FloatNullableFilter<"pitFuelTimeLossShift"> | number | null
  TimeRPM?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossShift"> | Date | string | null
  RefreshTime?: Prisma.DateTimeNullableFilter<"pitFuelTimeLossShift"> | Date | string | null
}, "RecordId">

export type pitFuelTimeLossShiftOrderByWithAggregationInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrderInput | Prisma.SortOrder
  Equipment?: Prisma.SortOrderInput | Prisma.SortOrder
  Status?: Prisma.SortOrderInput | Prisma.SortOrder
  Reason?: Prisma.SortOrderInput | Prisma.SortOrder
  Load?: Prisma.SortOrderInput | Prisma.SortOrder
  Location?: Prisma.SortOrderInput | Prisma.SortOrder
  UnitLoc?: Prisma.SortOrderInput | Prisma.SortOrder
  OperatorName?: Prisma.SortOrderInput | Prisma.SortOrder
  Crew?: Prisma.SortOrderInput | Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  FuelLoss?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrderInput | Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrderInput | Prisma.SortOrder
  TimeRPM?: Prisma.SortOrderInput | Prisma.SortOrder
  RefreshTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.pitFuelTimeLossShiftCountOrderByAggregateInput
  _avg?: Prisma.pitFuelTimeLossShiftAvgOrderByAggregateInput
  _max?: Prisma.pitFuelTimeLossShiftMaxOrderByAggregateInput
  _min?: Prisma.pitFuelTimeLossShiftMinOrderByAggregateInput
  _sum?: Prisma.pitFuelTimeLossShiftSumOrderByAggregateInput
}

export type pitFuelTimeLossShiftScalarWhereWithAggregatesInput = {
  AND?: Prisma.pitFuelTimeLossShiftScalarWhereWithAggregatesInput | Prisma.pitFuelTimeLossShiftScalarWhereWithAggregatesInput[]
  OR?: Prisma.pitFuelTimeLossShiftScalarWhereWithAggregatesInput[]
  NOT?: Prisma.pitFuelTimeLossShiftScalarWhereWithAggregatesInput | Prisma.pitFuelTimeLossShiftScalarWhereWithAggregatesInput[]
  RecordId?: Prisma.IntWithAggregatesFilter<"pitFuelTimeLossShift"> | number
  ShiftId?: Prisma.IntNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | number | null
  Equipment?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  Status?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  Reason?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  Load?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  Location?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  UnitLoc?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  OperatorName?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  Crew?: Prisma.StringNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | string | null
  IdFuelRate?: Prisma.IntWithAggregatesFilter<"pitFuelTimeLossShift"> | number
  FuelRate?: Prisma.FloatNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | number | null
  FuelLoss?: Prisma.FloatNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | number | null
  TimeFuelRate?: Prisma.DateTimeNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | Date | string | null
  IdRPM?: Prisma.IntWithAggregatesFilter<"pitFuelTimeLossShift"> | number
  RPM?: Prisma.FloatNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | number | null
  TimeRPM?: Prisma.DateTimeNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | Date | string | null
  RefreshTime?: Prisma.DateTimeNullableWithAggregatesFilter<"pitFuelTimeLossShift"> | Date | string | null
}

export type pitFuelTimeLossShiftCreateInput = {
  ShiftId?: number | null
  Equipment?: string | null
  Status?: string | null
  Reason?: string | null
  Load?: string | null
  Location?: string | null
  UnitLoc?: string | null
  OperatorName?: string | null
  Crew?: string | null
  IdFuelRate: number
  FuelRate?: number | null
  FuelLoss?: number | null
  TimeFuelRate?: Date | string | null
  IdRPM: number
  RPM?: number | null
  TimeRPM?: Date | string | null
  RefreshTime?: Date | string | null
}

export type pitFuelTimeLossShiftUncheckedCreateInput = {
  RecordId?: number
  ShiftId?: number | null
  Equipment?: string | null
  Status?: string | null
  Reason?: string | null
  Load?: string | null
  Location?: string | null
  UnitLoc?: string | null
  OperatorName?: string | null
  Crew?: string | null
  IdFuelRate: number
  FuelRate?: number | null
  FuelLoss?: number | null
  TimeFuelRate?: Date | string | null
  IdRPM: number
  RPM?: number | null
  TimeRPM?: Date | string | null
  RefreshTime?: Date | string | null
}

export type pitFuelTimeLossShiftUpdateInput = {
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossShiftUncheckedUpdateInput = {
  RecordId?: Prisma.IntFieldUpdateOperationsInput | number
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossShiftCreateManyInput = {
  ShiftId?: number | null
  Equipment?: string | null
  Status?: string | null
  Reason?: string | null
  Load?: string | null
  Location?: string | null
  UnitLoc?: string | null
  OperatorName?: string | null
  Crew?: string | null
  IdFuelRate: number
  FuelRate?: number | null
  FuelLoss?: number | null
  TimeFuelRate?: Date | string | null
  IdRPM: number
  RPM?: number | null
  TimeRPM?: Date | string | null
  RefreshTime?: Date | string | null
}

export type pitFuelTimeLossShiftUpdateManyMutationInput = {
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossShiftUncheckedUpdateManyInput = {
  RecordId?: Prisma.IntFieldUpdateOperationsInput | number
  ShiftId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Equipment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Load?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  UnitLoc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IdFuelRate?: Prisma.IntFieldUpdateOperationsInput | number
  FuelRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  FuelLoss?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeFuelRate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  IdRPM?: Prisma.IntFieldUpdateOperationsInput | number
  RPM?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  TimeRPM?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  RefreshTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type pitFuelTimeLossShiftCountOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  Equipment?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  Load?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  UnitLoc?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
  TimeRPM?: Prisma.SortOrder
  RefreshTime?: Prisma.SortOrder
}

export type pitFuelTimeLossShiftAvgOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
}

export type pitFuelTimeLossShiftMaxOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  Equipment?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  Load?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  UnitLoc?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
  TimeRPM?: Prisma.SortOrder
  RefreshTime?: Prisma.SortOrder
}

export type pitFuelTimeLossShiftMinOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  Equipment?: Prisma.SortOrder
  Status?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  Load?: Prisma.SortOrder
  Location?: Prisma.SortOrder
  UnitLoc?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  TimeFuelRate?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
  TimeRPM?: Prisma.SortOrder
  RefreshTime?: Prisma.SortOrder
}

export type pitFuelTimeLossShiftSumOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  ShiftId?: Prisma.SortOrder
  IdFuelRate?: Prisma.SortOrder
  FuelRate?: Prisma.SortOrder
  FuelLoss?: Prisma.SortOrder
  IdRPM?: Prisma.SortOrder
  RPM?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type pitFuelTimeLossShiftSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  RecordId?: boolean
  ShiftId?: boolean
  Equipment?: boolean
  Status?: boolean
  Reason?: boolean
  Load?: boolean
  Location?: boolean
  UnitLoc?: boolean
  OperatorName?: boolean
  Crew?: boolean
  IdFuelRate?: boolean
  FuelRate?: boolean
  FuelLoss?: boolean
  TimeFuelRate?: boolean
  IdRPM?: boolean
  RPM?: boolean
  TimeRPM?: boolean
  RefreshTime?: boolean
}, ExtArgs["result"]["pitFuelTimeLossShift"]>



export type pitFuelTimeLossShiftSelectScalar = {
  RecordId?: boolean
  ShiftId?: boolean
  Equipment?: boolean
  Status?: boolean
  Reason?: boolean
  Load?: boolean
  Location?: boolean
  UnitLoc?: boolean
  OperatorName?: boolean
  Crew?: boolean
  IdFuelRate?: boolean
  FuelRate?: boolean
  FuelLoss?: boolean
  TimeFuelRate?: boolean
  IdRPM?: boolean
  RPM?: boolean
  TimeRPM?: boolean
  RefreshTime?: boolean
}

export type pitFuelTimeLossShiftOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"RecordId" | "ShiftId" | "Equipment" | "Status" | "Reason" | "Load" | "Location" | "UnitLoc" | "OperatorName" | "Crew" | "IdFuelRate" | "FuelRate" | "FuelLoss" | "TimeFuelRate" | "IdRPM" | "RPM" | "TimeRPM" | "RefreshTime", ExtArgs["result"]["pitFuelTimeLossShift"]>

export type $pitFuelTimeLossShiftPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "pitFuelTimeLossShift"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    RecordId: number
    ShiftId: number | null
    Equipment: string | null
    Status: string | null
    Reason: string | null
    Load: string | null
    Location: string | null
    UnitLoc: string | null
    OperatorName: string | null
    Crew: string | null
    IdFuelRate: number
    FuelRate: number | null
    FuelLoss: number | null
    TimeFuelRate: Date | null
    IdRPM: number
    RPM: number | null
    TimeRPM: Date | null
    RefreshTime: Date | null
  }, ExtArgs["result"]["pitFuelTimeLossShift"]>
  composites: {}
}

export type pitFuelTimeLossShiftGetPayload<S extends boolean | null | undefined | pitFuelTimeLossShiftDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload, S>

export type pitFuelTimeLossShiftCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<pitFuelTimeLossShiftFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PitFuelTimeLossShiftCountAggregateInputType | true
  }

export interface pitFuelTimeLossShiftDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['pitFuelTimeLossShift'], meta: { name: 'pitFuelTimeLossShift' } }
  /**
   * Find zero or one PitFuelTimeLossShift that matches the filter.
   * @param {pitFuelTimeLossShiftFindUniqueArgs} args - Arguments to find a PitFuelTimeLossShift
   * @example
   * // Get one PitFuelTimeLossShift
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends pitFuelTimeLossShiftFindUniqueArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftFindUniqueArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PitFuelTimeLossShift that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {pitFuelTimeLossShiftFindUniqueOrThrowArgs} args - Arguments to find a PitFuelTimeLossShift
   * @example
   * // Get one PitFuelTimeLossShift
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends pitFuelTimeLossShiftFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PitFuelTimeLossShift that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossShiftFindFirstArgs} args - Arguments to find a PitFuelTimeLossShift
   * @example
   * // Get one PitFuelTimeLossShift
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends pitFuelTimeLossShiftFindFirstArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossShiftFindFirstArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PitFuelTimeLossShift that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossShiftFindFirstOrThrowArgs} args - Arguments to find a PitFuelTimeLossShift
   * @example
   * // Get one PitFuelTimeLossShift
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends pitFuelTimeLossShiftFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossShiftFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PitFuelTimeLossShifts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossShiftFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PitFuelTimeLossShifts
   * const pitFuelTimeLossShifts = await prisma.pitFuelTimeLossShift.findMany()
   * 
   * // Get first 10 PitFuelTimeLossShifts
   * const pitFuelTimeLossShifts = await prisma.pitFuelTimeLossShift.findMany({ take: 10 })
   * 
   * // Only select the `RecordId`
   * const pitFuelTimeLossShiftWithRecordIdOnly = await prisma.pitFuelTimeLossShift.findMany({ select: { RecordId: true } })
   * 
   */
  findMany<T extends pitFuelTimeLossShiftFindManyArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossShiftFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PitFuelTimeLossShift.
   * @param {pitFuelTimeLossShiftCreateArgs} args - Arguments to create a PitFuelTimeLossShift.
   * @example
   * // Create one PitFuelTimeLossShift
   * const PitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.create({
   *   data: {
   *     // ... data to create a PitFuelTimeLossShift
   *   }
   * })
   * 
   */
  create<T extends pitFuelTimeLossShiftCreateArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftCreateArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PitFuelTimeLossShifts.
   * @param {pitFuelTimeLossShiftCreateManyArgs} args - Arguments to create many PitFuelTimeLossShifts.
   * @example
   * // Create many PitFuelTimeLossShifts
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends pitFuelTimeLossShiftCreateManyArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossShiftCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PitFuelTimeLossShift.
   * @param {pitFuelTimeLossShiftDeleteArgs} args - Arguments to delete one PitFuelTimeLossShift.
   * @example
   * // Delete one PitFuelTimeLossShift
   * const PitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.delete({
   *   where: {
   *     // ... filter to delete one PitFuelTimeLossShift
   *   }
   * })
   * 
   */
  delete<T extends pitFuelTimeLossShiftDeleteArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftDeleteArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PitFuelTimeLossShift.
   * @param {pitFuelTimeLossShiftUpdateArgs} args - Arguments to update one PitFuelTimeLossShift.
   * @example
   * // Update one PitFuelTimeLossShift
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends pitFuelTimeLossShiftUpdateArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftUpdateArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PitFuelTimeLossShifts.
   * @param {pitFuelTimeLossShiftDeleteManyArgs} args - Arguments to filter PitFuelTimeLossShifts to delete.
   * @example
   * // Delete a few PitFuelTimeLossShifts
   * const { count } = await prisma.pitFuelTimeLossShift.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends pitFuelTimeLossShiftDeleteManyArgs>(args?: Prisma.SelectSubset<T, pitFuelTimeLossShiftDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PitFuelTimeLossShifts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossShiftUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PitFuelTimeLossShifts
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends pitFuelTimeLossShiftUpdateManyArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PitFuelTimeLossShift.
   * @param {pitFuelTimeLossShiftUpsertArgs} args - Arguments to update or create a PitFuelTimeLossShift.
   * @example
   * // Update or create a PitFuelTimeLossShift
   * const pitFuelTimeLossShift = await prisma.pitFuelTimeLossShift.upsert({
   *   create: {
   *     // ... data to create a PitFuelTimeLossShift
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PitFuelTimeLossShift we want to update
   *   }
   * })
   */
  upsert<T extends pitFuelTimeLossShiftUpsertArgs>(args: Prisma.SelectSubset<T, pitFuelTimeLossShiftUpsertArgs<ExtArgs>>): Prisma.Prisma__pitFuelTimeLossShiftClient<runtime.Types.Result.GetResult<Prisma.$pitFuelTimeLossShiftPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PitFuelTimeLossShifts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossShiftCountArgs} args - Arguments to filter PitFuelTimeLossShifts to count.
   * @example
   * // Count the number of PitFuelTimeLossShifts
   * const count = await prisma.pitFuelTimeLossShift.count({
   *   where: {
   *     // ... the filter for the PitFuelTimeLossShifts we want to count
   *   }
   * })
  **/
  count<T extends pitFuelTimeLossShiftCountArgs>(
    args?: Prisma.Subset<T, pitFuelTimeLossShiftCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PitFuelTimeLossShiftCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PitFuelTimeLossShift.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PitFuelTimeLossShiftAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PitFuelTimeLossShiftAggregateArgs>(args: Prisma.Subset<T, PitFuelTimeLossShiftAggregateArgs>): Prisma.PrismaPromise<GetPitFuelTimeLossShiftAggregateType<T>>

  /**
   * Group by PitFuelTimeLossShift.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pitFuelTimeLossShiftGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends pitFuelTimeLossShiftGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: pitFuelTimeLossShiftGroupByArgs['orderBy'] }
      : { orderBy?: pitFuelTimeLossShiftGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, pitFuelTimeLossShiftGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPitFuelTimeLossShiftGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the pitFuelTimeLossShift model
 */
readonly fields: pitFuelTimeLossShiftFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for pitFuelTimeLossShift.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__pitFuelTimeLossShiftClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the pitFuelTimeLossShift model
 */
export interface pitFuelTimeLossShiftFieldRefs {
  readonly RecordId: Prisma.FieldRef<"pitFuelTimeLossShift", 'Int'>
  readonly ShiftId: Prisma.FieldRef<"pitFuelTimeLossShift", 'Int'>
  readonly Equipment: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly Status: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly Reason: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly Load: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly Location: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly UnitLoc: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly OperatorName: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly Crew: Prisma.FieldRef<"pitFuelTimeLossShift", 'String'>
  readonly IdFuelRate: Prisma.FieldRef<"pitFuelTimeLossShift", 'Int'>
  readonly FuelRate: Prisma.FieldRef<"pitFuelTimeLossShift", 'Float'>
  readonly FuelLoss: Prisma.FieldRef<"pitFuelTimeLossShift", 'Float'>
  readonly TimeFuelRate: Prisma.FieldRef<"pitFuelTimeLossShift", 'DateTime'>
  readonly IdRPM: Prisma.FieldRef<"pitFuelTimeLossShift", 'Int'>
  readonly RPM: Prisma.FieldRef<"pitFuelTimeLossShift", 'Float'>
  readonly TimeRPM: Prisma.FieldRef<"pitFuelTimeLossShift", 'DateTime'>
  readonly RefreshTime: Prisma.FieldRef<"pitFuelTimeLossShift", 'DateTime'>
}
    

// Custom InputTypes
/**
 * pitFuelTimeLossShift findUnique
 */
export type pitFuelTimeLossShiftFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossShift to fetch.
   */
  where: Prisma.pitFuelTimeLossShiftWhereUniqueInput
}

/**
 * pitFuelTimeLossShift findUniqueOrThrow
 */
export type pitFuelTimeLossShiftFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossShift to fetch.
   */
  where: Prisma.pitFuelTimeLossShiftWhereUniqueInput
}

/**
 * pitFuelTimeLossShift findFirst
 */
export type pitFuelTimeLossShiftFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossShift to fetch.
   */
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossShifts to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossShiftOrderByWithRelationInput | Prisma.pitFuelTimeLossShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for pitFuelTimeLossShifts.
   */
  cursor?: Prisma.pitFuelTimeLossShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pitFuelTimeLossShifts.
   */
  distinct?: Prisma.PitFuelTimeLossShiftScalarFieldEnum | Prisma.PitFuelTimeLossShiftScalarFieldEnum[]
}

/**
 * pitFuelTimeLossShift findFirstOrThrow
 */
export type pitFuelTimeLossShiftFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossShift to fetch.
   */
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossShifts to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossShiftOrderByWithRelationInput | Prisma.pitFuelTimeLossShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for pitFuelTimeLossShifts.
   */
  cursor?: Prisma.pitFuelTimeLossShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pitFuelTimeLossShifts.
   */
  distinct?: Prisma.PitFuelTimeLossShiftScalarFieldEnum | Prisma.PitFuelTimeLossShiftScalarFieldEnum[]
}

/**
 * pitFuelTimeLossShift findMany
 */
export type pitFuelTimeLossShiftFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * Filter, which pitFuelTimeLossShifts to fetch.
   */
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pitFuelTimeLossShifts to fetch.
   */
  orderBy?: Prisma.pitFuelTimeLossShiftOrderByWithRelationInput | Prisma.pitFuelTimeLossShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing pitFuelTimeLossShifts.
   */
  cursor?: Prisma.pitFuelTimeLossShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pitFuelTimeLossShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pitFuelTimeLossShifts.
   */
  skip?: number
  distinct?: Prisma.PitFuelTimeLossShiftScalarFieldEnum | Prisma.PitFuelTimeLossShiftScalarFieldEnum[]
}

/**
 * pitFuelTimeLossShift create
 */
export type pitFuelTimeLossShiftCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * The data needed to create a pitFuelTimeLossShift.
   */
  data: Prisma.XOR<Prisma.pitFuelTimeLossShiftCreateInput, Prisma.pitFuelTimeLossShiftUncheckedCreateInput>
}

/**
 * pitFuelTimeLossShift createMany
 */
export type pitFuelTimeLossShiftCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many pitFuelTimeLossShifts.
   */
  data: Prisma.pitFuelTimeLossShiftCreateManyInput | Prisma.pitFuelTimeLossShiftCreateManyInput[]
}

/**
 * pitFuelTimeLossShift update
 */
export type pitFuelTimeLossShiftUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * The data needed to update a pitFuelTimeLossShift.
   */
  data: Prisma.XOR<Prisma.pitFuelTimeLossShiftUpdateInput, Prisma.pitFuelTimeLossShiftUncheckedUpdateInput>
  /**
   * Choose, which pitFuelTimeLossShift to update.
   */
  where: Prisma.pitFuelTimeLossShiftWhereUniqueInput
}

/**
 * pitFuelTimeLossShift updateMany
 */
export type pitFuelTimeLossShiftUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update pitFuelTimeLossShifts.
   */
  data: Prisma.XOR<Prisma.pitFuelTimeLossShiftUpdateManyMutationInput, Prisma.pitFuelTimeLossShiftUncheckedUpdateManyInput>
  /**
   * Filter which pitFuelTimeLossShifts to update
   */
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  /**
   * Limit how many pitFuelTimeLossShifts to update.
   */
  limit?: number
}

/**
 * pitFuelTimeLossShift upsert
 */
export type pitFuelTimeLossShiftUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * The filter to search for the pitFuelTimeLossShift to update in case it exists.
   */
  where: Prisma.pitFuelTimeLossShiftWhereUniqueInput
  /**
   * In case the pitFuelTimeLossShift found by the `where` argument doesn't exist, create a new pitFuelTimeLossShift with this data.
   */
  create: Prisma.XOR<Prisma.pitFuelTimeLossShiftCreateInput, Prisma.pitFuelTimeLossShiftUncheckedCreateInput>
  /**
   * In case the pitFuelTimeLossShift was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.pitFuelTimeLossShiftUpdateInput, Prisma.pitFuelTimeLossShiftUncheckedUpdateInput>
}

/**
 * pitFuelTimeLossShift delete
 */
export type pitFuelTimeLossShiftDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
  /**
   * Filter which pitFuelTimeLossShift to delete.
   */
  where: Prisma.pitFuelTimeLossShiftWhereUniqueInput
}

/**
 * pitFuelTimeLossShift deleteMany
 */
export type pitFuelTimeLossShiftDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which pitFuelTimeLossShifts to delete
   */
  where?: Prisma.pitFuelTimeLossShiftWhereInput
  /**
   * Limit how many pitFuelTimeLossShifts to delete.
   */
  limit?: number
}

/**
 * pitFuelTimeLossShift without action
 */
export type pitFuelTimeLossShiftDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pitFuelTimeLossShift
   */
  select?: Prisma.pitFuelTimeLossShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pitFuelTimeLossShift
   */
  omit?: Prisma.pitFuelTimeLossShiftOmit<ExtArgs> | null
}
