
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  fuelTimeLoss_1: 'fuelTimeLoss_1',
  pitFuelTimeLossShift: 'pitFuelTimeLossShift',
  pitFuelTimeLossCurrent: 'pitFuelTimeLossCurrent'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
  Snapshot: 'Snapshot'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const FuelTimeLoss_1ScalarFieldEnum = {
  RecordId: 'RecordId',
  DateYear: 'DateYear',
  DateMonth: 'DateMonth',
  OperatorName: 'OperatorName',
  Crew: 'Crew',
  Reason: 'Reason',
  LossFuel: 'LossFuel',
  LossTime: 'LossTime'
} as const

export type FuelTimeLoss_1ScalarFieldEnum = (typeof FuelTimeLoss_1ScalarFieldEnum)[keyof typeof FuelTimeLoss_1ScalarFieldEnum]


export const PitFuelTimeLossShiftScalarFieldEnum = {
  RecordId: 'RecordId',
  ShiftId: 'ShiftId',
  Equipment: 'Equipment',
  Status: 'Status',
  Reason: 'Reason',
  Load: 'Load',
  Location: 'Location',
  UnitLoc: 'UnitLoc',
  OperatorName: 'OperatorName',
  Crew: 'Crew',
  IdFuelRate: 'IdFuelRate',
  FuelRate: 'FuelRate',
  FuelLoss: 'FuelLoss',
  TimeFuelRate: 'TimeFuelRate',
  IdRPM: 'IdRPM',
  RPM: 'RPM',
  TimeRPM: 'TimeRPM',
  RefreshTime: 'RefreshTime'
} as const

export type PitFuelTimeLossShiftScalarFieldEnum = (typeof PitFuelTimeLossShiftScalarFieldEnum)[keyof typeof PitFuelTimeLossShiftScalarFieldEnum]


export const PitFuelTimeLossCurrentScalarFieldEnum = {
  RecordId: 'RecordId',
  ShiftId: 'ShiftId',
  Equipment: 'Equipment',
  Status: 'Status',
  Reason: 'Reason',
  Load: 'Load',
  Location: 'Location',
  UnitLoc: 'UnitLoc',
  OperatorName: 'OperatorName',
  Crew: 'Crew',
  IdFuelRate: 'IdFuelRate',
  FuelRate: 'FuelRate',
  FuelLoss: 'FuelLoss',
  TimeFuelRate: 'TimeFuelRate',
  IdRPM: 'IdRPM',
  RPM: 'RPM',
  TimeRPM: 'TimeRPM',
  RefreshTime: 'RefreshTime'
} as const

export type PitFuelTimeLossCurrentScalarFieldEnum = (typeof PitFuelTimeLossCurrentScalarFieldEnum)[keyof typeof PitFuelTimeLossCurrentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

